#THIS SCRIPT EXECUTES AN ANALYSIS OF EIGHT STUDIES
#THE RESULTS FOR EACH STUDY ARE STORED IN FILES Inputfile1.txt THROUGH Inputfile8.txt

#LOAD THE FIRST EIGHT INPUT FILES

# UNCOMMENT THE NEXT LINE TO ENABLE GenomicControl CORRECTION
# GENOMICCONTROL ON

SCHEME STDERR

# === DESCRIBE AND PROCESS THE FIRST INPUT FILE ===
MARKER SNP
ALLELE A1 A2
EFFECT BETA
PVALUE P
STDERR SE
PROCESS st1.metal_in
PROCESS st2.metal_in
PROCESS st3.metal_in
PROCESS st4.metal_in
PROCESS st5.metal_in
#

# === CARRY OUT AN INTERIM ANALYSIS OF THE FIRST FOUR FILES ===
OUTFILE pcsk9_direct .tbl
ANALYZE

# LOAD THE indirect INPUT FILES
MARKER SNP
ALLELE A1 A2
EFFECT BETA
PVALUE P
STDERR SE
PROCESS st6.metal_in

OUTFILE pcsk9_all .tbl
ANALYZE

QUIT
